### ISSUE TITLE
GPU Memory

### ISSUE THREAD

**Issue by MaskXman** [clear-nus/edc#2]
Could you please tell me the min of GPU memory?
I run run.py in 24g gtx 4090 memory out.

**Comment by hanw** [comment]
I got the same GPU out of memory error.
Traceback (most recent call last):
  File "/home/hanwang/p/edc/run.py", line 106, in <module>
    edc = EDC(**args)
  File "/home/hanwang/p/edc/edc/edc_framework.py", line 94, in __init__
    schema_canonicalization_embedding_model = MistralForSequenceEmbedding.from_pretrained(
  File "/home/hanwang/miniconda3/envs/edc-new/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3531, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/hanwang/miniconda3/envs/edc-new/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3958, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/hanwang/miniconda3/envs/edc-new/lib/python3.9/site-packages/transformers/modeling_utils.py", line 812, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/hanwang/miniconda3/envs/edc-new/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 399, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU

**Comment by bzhangj13zzz** [comment]
We need to load two Mistral-7b embedding models, one for canonicalization and one for refinement. If you also use Mistral-7b for the prompting stuff, that would be around 3 * 28 = 84G required. I would recommend using smaller or quantized models if needed.

**Comment by bzhangj13zzz** [comment]
I understand this memory requirement is very high for common setups. For now, the code is mainly for the reproduction of experiment results shown in the paper instead of a general tool for knowledge graph construction and open information extraction. We do plan to modify the code to allow easier and more modular use of smaller models that can be run on household machines.
