### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by hjkim811** [clear-nus/edc#7]
Hi, 

I'm trying to run Self Canonicalization with the provided code in a cloud computing platform (4 x A100),
but getting this error continuously.

Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/edc/run.py", line 106, in <module>
    edc = EDC(**args)
  File "/content/drive/MyDrive/edc/edc/edc_framework.py", line 94, in __init__
    schema_canonicalization_embedding_model = MistralForSequenceEmbedding.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py", line 3531, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py", line 3958, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py", line 794, in _load_state_dict_into_meta_model
    raise ValueError(f"{param_name} doesn't have any device set.")
ValueError: embed_tokens.weight doesn't have any device set.

Do you have any idea why this is happening?

**Comment by Harsh-Yadav-02** [comment]
try setting all `device_map="auto"` to `device_map="cpu"` in edc_framework.py.

**Comment by hjkim811** [comment]
It solved the issue, thank you!
